import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { fetchMemes } from "~/api";
import type { Meme } from "~/api";
import { useEffect, useState } from "react";


const Home: NextPage = () => {
  const [memes, setMemes] = useState<Meme[] | null>(null);

  useEffect(() => {
    fetchMemes("normal", 9).then((memes) => {
      setMemes(memes);
    });
  }, []);


  return (
    <>
      <Head>
        <title>MemesAPI</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#002b74] to-[#090024]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Welcome to <span className="text-[hsl(12,100%,64%)]">Memes</span>API
          </h1>


          <div className="grid grid-flow-row-dense grid-cols-1 gap-2 md:grid-cols-3 sm:grid-cols-2 lg:grid-cols-4">
            {
              memes?.map((meme) => (
                <a className="rounded-2xl bg-white/10 p-2 text-white hover:bg-white/20 shadow-lg"
                  href={meme.original}
                  target="_blank"
                >
                  <h4 className="text-md p-1 font-bold ">{meme.title}</h4>
                  <img src={meme.url} alt={meme.title} className="w-full rounded-xl" />
                  <h4 className="text-sm p-2  md:h-6 sm:h-9 h-9 text-orange-200">- {meme.author}</h4>
                </a>
              ))
            }
          </div>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="#"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Github Repo →</h3>
              <div className="text-lg">
                If you liked this project, please consider giving it a star on Github. It helps me out a lot!
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="#"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Other Projects →</h3>
              <div className="text-lg">
                I have a lot of other projects that you might be interested in. Check them out!
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="#"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Twitter →</h3>
              <div className="text-lg">
                I post updates about my projects on Twitter. Follow me to stay up to date!
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="#"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Portfolio →</h3>
              <div className="text-lg">
                I have a portfolio website where you can see all of my projects. Check it out!
              </div>
            </Link>
          </div>

        </div>
      </main>
    </>
  );
};

export default Home;
